#!/usr/bin/env python3
"""
diag_signal_generation_flow.py

Trace WHY signals are generated by showing:
  1. All candidates (executed + rejected) for a symbol/date
  2. Why rejected candidates failed (confluence too low, wrong regime, etc.)
  3. Why executed ones passed (strategy vote breakdown, confluence score)

Usage:
    python diag_signal_generation_flow.py [--symbol NIFTY] [--today] [--all-candidates]
"""

import sqlite3
import json
from datetime import datetime
from pathlib import Path
from typing import List, Dict

def get_signal_candidates(symbol_filter=None, today_only=True, include_rejected=True):
    """Query signal_log for all candidates (executed + rejected)."""
    
    db_path = Path("signal_log.db")
    if not db_path.exists():
        print(f"❌ {db_path} not found")
        return [], []
    
    try:
        with sqlite3.connect(db_path) as conn:
            conn.row_factory = sqlite3.Row
            
            where_clauses = []
            params = []
            
            if today_only:
                today = datetime.now().strftime("%Y-%m-%d")
                where_clauses.append("signal_date = ?")
                params.append(today)
            
            if symbol_filter:
                where_clauses.append("symbol = ?")
                params.append(symbol_filter.upper())
            
            where_sql = " AND ".join(where_clauses) if where_clauses else "1=1"
            
            # Get executed
            query_exec = f"""
            SELECT 
                id, signal_date, signal_time, symbol, strategy, side,
                score, raw_score, confluence, n_agree, agreeing_strats,
                executed, rejection_reason,
                option_strike, option_dte, option_style, option_premium,
                regime, india_vix, pcr_atm, expiry_regime
            FROM signal_log
            WHERE {where_sql} AND executed = 1
            ORDER BY signal_date DESC, signal_time DESC
            LIMIT 100
            """
            
            executed = [dict(row) for row in conn.execute(query_exec, params).fetchall()]
            
            # Get rejected
            rejected = []
            if include_rejected:
                query_rej = f"""
                SELECT 
                    id, signal_date, signal_time, symbol, strategy, side,
                    score, raw_score, confluence, n_agree, agreeing_strats,
                    executed, rejection_reason,
                    option_strike, option_dte, option_style,
                    regime, india_vix, pcr_atm
                FROM signal_log
                WHERE {where_sql} AND executed = 0
                ORDER BY signal_date DESC, signal_time DESC
                LIMIT 100
                """
                rejected = [dict(row) for row in conn.execute(query_rej, params).fetchall()]
            
            return executed, rejected
    
    except Exception as e:
        print(f"❌ Database error: {e}")
        return [], []

def format_signal_flow(executed: List[Dict], rejected: List[Dict]) -> str:
    """Format signal flow for audit."""
    
    output = []
    output.append("\n" + "="*150)
    output.append("SIGNAL GENERATION FLOW — Why Signals Pass/Fail")
    output.append("="*150 + "\n")
    
    # ─────────────────────────────────────────────────────────────────────────
    # EXECUTED SIGNALS
    # ─────────────────────────────────────────────────────────────────────────
    output.append("\n✅ EXECUTED SIGNALS (Passed all gates & generated option trades):\n")
    
    if executed:
        for i, sig in enumerate(executed, 1):
            output.append(f"[{i}] {sig.get('signal_date')} {sig.get('signal_time')}")
            output.append(f"    Symbol:       {sig.get('symbol')}")
            output.append(f"    Strategy:     {sig.get('strategy')}")
            output.append(f"    Direction:    {sig.get('side')}")
            output.append(f"    Score:        {sig.get('score', 0):.2f} (raw: {sig.get('raw_score', 0):.2f})")
            output.append(f"    Confluence:   {sig.get('confluence')} ({sig.get('n_agree', 1)} strategies agreed)")
            
            agreeing = sig.get('agreeing_strats', '[]')
            try:
                if isinstance(agreeing, str):
                    agreeing_list = json.loads(agreeing)
                else:
                    agreeing_list = agreeing
                if agreeing_list:
                    output.append(f"    Strategies:   {', '.join(agreeing_list[:3])}")
                    if len(agreeing_list) > 3:
                        output.append(f"                  ... +{len(agreeing_list)-3} more")
            except:
                pass
            
            # If option trade, show strike selection
            if sig.get('option_strike'):
                output.append(f"    Option:       {sig.get('option_strike')} {sig.get('option_style')} (DTE={sig.get('option_dte')})")
            
            output.append(f"    Market:       {sig.get('regime')} | VIX={sig.get('india_vix', 0):.1f} | PCR={sig.get('pcr_atm', 0):.2f}")
            output.append("")
    else:
        output.append("    (No executed signals yet)\n")
    
    # ─────────────────────────────────────────────────────────────────────────
    # REJECTED SIGNALS (Why they didn't execute)
    # ─────────────────────────────────────────────────────────────────────────
    output.append("\n" + "-"*150)
    output.append("\n❌ REJECTED CANDIDATES (Why they were filtered out):\n")
    
    if rejected:
        # Group by rejection reason
        by_reason = {}
        for sig in rejected:
            reason = sig.get('rejection_reason', 'UNKNOWN')
            if reason not in by_reason:
                by_reason[reason] = []
            by_reason[reason].append(sig)
        
        for reason, sigs in sorted(by_reason.items(), key=lambda x: -len(x[1])):
            output.append(f"\n  📌 {reason} ({len(sigs)} candidates):")
            
            for sig in sigs[:3]:  # Show top 3 per reason
                output.append(f"     • {sig.get('signal_date')} {sig.get('signal_time')} — "
                            f"{sig.get('symbol')} {sig.get('strategy')} "
                            f"(score={sig.get('score', 0):.1f}, confluence={sig.get('confluence')})")
            
            if len(sigs) > 3:
                output.append(f"     ... and {len(sigs)-3} more with this reason")
        
        output.append("")
    else:
        output.append("    (No rejected candidates)\n")
    
    # ─────────────────────────────────────────────────────────────────────────
    # GATE SEQUENCE (explains why candidates pass/fail)
    # ─────────────────────────────────────────────────────────────────────────
    output.append("\n" + "="*150)
    output.append("\nGATE SEQUENCE (in order):\n")
    
    gates = [
        ("1. FNO Ban Check", "is_fno_banned(symbol)", "Reject F&O banned symbols (NIFTY_FO_BAN_LIST)"),
        ("2. Symbol Blacklist", "check_and_blacklist_symbol(symbol)", "Symbol in manual blacklist or 3+ SL hits in 14 days"),
        ("3. SL Cooldown", "is_in_sl_cooldown(symbol)", "Symbol paused for 30min after stop hit"),
        ("4. Manual Pause", "symbol in paused_symbols.json", "Strategy manually paused via /pause_sym"),
        ("5. Regime Gate", "should_strategy_run_in_regime(strategy, regime)", "Strategy incompatible with current regime (CHOPPY/TREND/etc)"),
        ("6. Auto-Disable", "strategy_performance_matrix.should_run_strategy()", "Strategy disabled (poor win_rate or banned)"),
        ("7. Data Quality", "market_quality_block_live", "Market data degraded (low volume/volatility)"),
        ("8. Confluence Gate", "confluence >= MIN_CONFLUENCE_SCORE", "Not enough strategies voted for same direction"),
        ("9. Score Gate", "score >= POST_CONFLUENCE_MIN_SCORE", "Score too low after confluence check"),
        ("10. Volume Gate", "volume_ratio >= MIN_VOLUME_RATIO_ENTRY", "Insufficient volume at entry"),
        ("11. HTF Alignment", "htf_bias == signal_direction", "Intraday direction vs higher timeframe conflict"),
        ("12. Risk Gate", "risk_manager.can_add_position(symbol)", "Risk limits reached (max positions, daily loss limit, correlation, etc)"),
        ("13. Execution", "broker.place_order(qty, price, sl, target)", "Order placed on broker — SIGNAL EXECUTED"),
    ]
    
    for gate_name, gate_check, description in gates:
        output.append(f"  {gate_name:<20} | {gate_check:<45} | {description}")
    
    output.append("")
    output.append("="*150 + "\n")
    
    return "\n".join(output)

def main():
    import argparse
    parser = argparse.ArgumentParser(description="Trace signal generation flow")
    parser.add_argument("--symbol", type=str, help="Filter by symbol (e.g. NIFTY)")
    parser.add_argument("--all-dates", action="store_true", help="Show all dates, not just today")
    parser.add_argument("--no-rejected", action="store_true", help="Hide rejected candidates")
    
    args = parser.parse_args()
    
    executed, rejected = get_signal_candidates(
        symbol_filter=args.symbol,
        today_only=not args.all_dates,
        include_rejected=not args.no_rejected
    )
    
    print(format_signal_flow(executed, rejected))
    
    if not executed and not rejected:
        print("⚠️  No signal data found. Run the trading system first to populate signal_log.db")

if __name__ == "__main__":
    main()
